### PR TITLE
Generalizing

### PR DESCRIPTION
**Pull request by arena**

### CODE REVIEW

**Comment by arena** [comment]
I just wanted the localizable version to be the master branch. It runs fine locally on my system.

**Comment by siruguri** [comment]
Will take a whack at merge to master before I leave, though might have to
wait to return to US due to Internet slowness over here...

**Comment by siruguri** [comment]
Will take a whack at merge to master before I leave, though might have to
wait to return to US due to Internet slowness over here.

**Comment by arena** [comment]
Hi!
I think I already did the merge.

Then I did some advanced stuff to merge our fork over to Oak72. :)

**Pull request merged**
